### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by kimreyio** [myfreeweb/node-red-contrib-nut-ups#3]
I am getting the following error on my Node-Red Flow... I was sending a flow.start using an inject node.

`TypeError: Cannot create property 'low' on string '100'`

Here is my upsc output...

````
homeassistant:~/.node-red# upsc CyberPowerOR700@10.1.1.1
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 20
battery.mfr.date: CPS
battery.runtime: 1680
battery.runtime.low: 300
battery.type: PbAcid
battery.voltage: 14.1
battery.voltage.nominal: 12
device.mfr: CPS
device.model: UPS OR700
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.data: CyberPower HID 0.4
driver.version.internal: 0.41
input.transfer.high: 140
input.transfer.low: 90
input.voltage: 123.0
input.voltage.nominal: 120
output.voltage: 123.0
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.delay.start: 30
ups.load: 29
ups.mfr: CPS
ups.model: UPS OR700
ups.productid: 0601
ups.realpower.nominal: 400
ups.status: OL
ups.test.result: Done and passed
ups.timer.shutdown: -60
ups.timer.start: -60
ups.vendorid: 0764

**Comment by valpackett** [comment]
If you look at the source code, the string `low` is not there… So that's probably not coming from this node, it's from something further down your pipeline that processes it.

**Comment by tema-san** [comment]
[nut-ups.js.txt](https://github.com/myfreeweb/node-red-contrib-nut-ups/files/1492819/nut-ups.js.txt)
just replace nut-ups.js with this
an you will get
---
21 Nov 20:06:53 - [info] [debug:4f4a9c73.7bc654]
{ battery_charge: '95',
  battery_charge_low: '10',
  battery_charge_warning: '30',
  battery_date: '2009/12/23',
  battery_runtime: '24320',
  battery_type: 'PbAc',
  device_mfr: 'POWERCOM Co.,LTD',
  device_model: 'HID UPS Battery',
  device_serial: '004-0D9F-000',
  device_type: 'ups',
  driver_name: 'usbhid-ups',
  driver_parameter_pollfreq: '30',
  driver_parameter_pollinterval: '2',
  driver_parameter_port: 'auto',
  driver_parameter_productid: '0004',
  driver_parameter_synchronous: 'no',
  driver_parameter_vendorid: '0d9f',
  driver_version: '2.7.4',
  driver_version_data: 'PowerCOM HID 0.5',
  driver_version_internal: '0.41',
  input_frequency: '50.0',
  input_voltage: '230.0',
  input_voltage_nominal: '220',
  output_frequency: '50.0',
  output_voltage: '230.0',
  output_voltage_nominal: '220',
  ups_beeper_status: 'enabled',
  ups_date: '2009/12/23',
  ups_delay_shutdown: '20',
  ups_delay_start: '60',
  ups_load: '5',
  ups_mfr: 'POWERCOM Co.,LTD',
  ups_model: 'HID UPS Battery',
  ups_productid: '0004',
  ups_serial: '004-0D9F-000',
  ups_status: 'OL CHRG',
  ups_test_result: 'Done and passed',
  ups_timer_shutdown: '0',
  ups_timer_start: '0',
  ups_vendorid: '0d9f' }


the problem was in read_only object properties

https://stackoverflow.com/questions/27519836/uncaught-typeerror-cannot-assign-to-read-only-property

**Comment by valpackett** [comment]
This was fixed in #2. Released v1.0.2.

**Comment by tema-san** [comment]
not fixed. 
fresh install of contrib

21 Nov 19:48:00 - [red] Uncaught Exception:
21 Nov 19:48:00 - TypeError: Cannot assign to read only property 'low' of 95
    at /home/pi/.node-red/node_modules/node-red-contrib-nut-ups/nut-ups/nut-ups.js:26:38
    at Array.forEach (native)

**Comment by valpackett** [comment]
Make sure you actually install 1.0.2. "Fresh install" might install from cache.
