### ISSUE TITLE
How to access if ups uses password access?

### ISSUE THREAD

**Issue by sgrayban** [myfreeweb/node-red-contrib-nut-ups#9]
Tried the normal user:pass@IP and that didnt seem to work. It keeps coming up with unknown UPS. Not sure if I am doing something wrong...

**Comment by valpackett** [comment]
The `@` is used for UPS name. Authentication was not supported. I've added it in git master but it's completely untested (I don't have a node-red setup right now). Please try installing the git version, it should have username and password fields.

**Comment by sgrayban** [comment]
Ok stupid question... how do I install using git version?

**Comment by sgrayban** [comment]
nm _ i got it working -- thanks for fixing the code :)

**Comment by S474N** [comment]
In Palette is another version than here?

**Comment by feuerwasser85** [comment]
I have the same problem. How did you get it to work @sgrayban?
Is there any chance that this change gets into the official node-red store?

**Comment by valpackett** [comment]
I've released 1.2.0 to npm, so this should be updated now.

**Comment by derbmann** [comment]
Still shows and installs 1.1.0 in "manage pallet"
https://flows.nodered.org/node/node-red-contrib-nut-ups

**Comment by valpackett** [comment]
I have no idea how the flows gallery works, I haven't really touched Node-RED in years… could you contact the Node-RED maintainers about that?

**Comment by miaszh** [comment]
> nm _ i got it working -- thanks for fixing the code :)

@sgrayban 
Hi, could you share how did you get it to work? how did you install the updated version?

Thanks.
